name: curereach
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  email_validator: ^3.0.0
  http: ^0.13.4
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4  # ✅ For storing files (optional)
  firebase_messaging: ^15.2.4 # ✅ For push notifications
  connectivity_plus: ^6.1.3   # ✅ To check internet connection
  firebase_database: ^11.3.4
  url_launcher: ^6.3.1
  emailjs: ^1.0.0
  stream_video_flutter: ^0.8.1
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  flutter_local_notifications: ^18.0.1
  dialogflow_flutter: ^1.0.0
  flutter_dotenv: ^5.1.0
  jitsi_meet_wrapper: ^0.2.0+1
  jitsi_meet_flutter_sdk: ^11.0.2
  qr_flutter: ^4.1.0


dependency_overrides:
  http: ^0.13.3 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png  # Ensure all these files exist
    - assets/google.png
    - assets/facebook.png
    - assets/curereachbot-key.json
    - assets/apple.png
    - assets/urology.png
    - assets/cardiology.png
    - assets/radiology.png
    - assets/ophthalmology.png
    - assets/obstetrician.png
    - assets/dermatology.png
    - assets/doctor.png
    - assets/patient.png
    - assets/avatar.png
    
