// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    if (defaultTargetPlatform == TargetPlatform.android) return android;
    throw UnsupportedError('This platform is not supported.');
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR API KEY',
    appId: 'YOUT API ID',
    messagingSenderId: 'YOUR ID',
    projectId: 'curereach-15f21',
    authDomain: 'curereach-15f21.firebaseapp.com',
    storageBucket: 'curereach-15f21.appspot.com',
    measurementId: 'G-SQDH6X5Z3P',
    databaseURL:
        'https://curereach-15f21-default-rtdb.firebaseio.com', // ✅ Added database URL
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR API KEY',
    appId: 'YOUR API ID',
    messagingSenderId: 'YOUR ID',
    projectId: 'curereach-15f21',
    storageBucket: 'curereach-15f21.appspot.com',
    databaseURL:
        'https://curereach-15f21-default-rtdb.firebaseio.com', // ✅ Added database URL
  );
}
